### PR TITLE
Configure nonce also for preloaded scripts

### PR DESCRIPTION
**Pull request by jukben**
###  Summary

Solving #84 

Does it make sense for you? Should I write test for this it? 👍 

### Requirements (place an `x` in each `[ ]`)

* [x] I've read and understood the [Contributing Guidelines](https://github.com/slackhq/csp-html-webpack-plugin/blob/master/.github/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've written tests to cover the new code and functionality included in this PR.
* [x] I've read, agree to, and signed the [Contributor License Agreement (CLA)](https://cla-assistant.io/slackhq/hack-json-schema).

### CODE REVIEW

**Comment by AnujRNair** [comment]
Thanks for the contribution!

It looks like you can also use preload links to load web workers, and these should be added to the CSP via the [child-src](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/child-src) directive. At the moment, this change will always add the nonce to the `script-src` directive.

I think we could solve for this in a few ways:
- Add an additional option to enable generation for preload links, and add them to the `script-src`. However, this won't work for applications that want to preload both js files and workers
- Ask developers to add a data tag to `link`s that they want to preload and add to the `script-src`. We could then target it with `link[rel="preload"][as="script"][data-csp="script-src"]`. This would then be extendible to workers in the future, and allow us to add `[data-csp="child-src"]` to generate those nonces too.

I'm leaning towards the second given it would result in a correct csp implementation, and is flexible for the future. Do you agree?

If so, could you make the change and add tests?

Thanks!

**Comment by jukben** [comment]
Hey @AnujRNair sorry for getting back so late I somehow missed the notification 🤦 . 

So if I understand correctly you propose to document possibility to add `data-csp=` tag to links (for now). Thus the usage would be something like (in my case #84 see the original issue)

```
<link rel="preload" href="..." as="script" crossorigin="anonymous" data-csp="script-src">
```

In the future we could introduce that `data-csp="child-src"` and reiterate on it, but that's something we should wait once the real need is there, I agree, so let's descope the complexity now 👍 

If we are on the same page, I will wrap it up with test and we are ready to go 🚀

**Comment by AnujRNair** [comment]
Sorry for the delay - yes this is what I was thinking!
If you wouldn't mind adding this in with test, that would be great
Thanks

**Comment by jukben** [comment]
Hey @AnujRNair I think this should do the trick 🚀

**Comment by melloware** [comment]
@jukben OK I forked this repo and published it to NPM including this change.

GitHub: https://github.com/melloware/csp-webpack-plugin

NPM: https://www.npmjs.com/package/@melloware/csp-webpack-plugin

**Pull request closed without merging**
